version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
      - primo-explore-eluna-workshop
      - quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:latest
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: https://arizona-asu-primosb.hosted.exlibrisgroup.com:443
      VIEW: ${VIEW-ASU}
    ports:
    - 8003:8003
    - 3001:3001
    # volumes:
    # - ./primo-explore/custom:/app/primo-explore/custom/

  create-package:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
      - primo-explore-eluna-workshop
      - quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:latest
    image: primo-explore-eluna-workshop
    environment:
      PROXY_SERVER: https://arizona-asu-primosb.hosted.exlibrisgroup.com:443
      VIEW: ${VIEW-ASU}
    ports:
    - 8003:8003
    - 3001:3001
    command: yarn create-package
    # volumes:
    # - ./primo-explore/custom:/app/primo-explore/custom/
    # - ./packages:/app/packages/

  e2e:
    build:
      context: ./e2e-cypress
      cache_from:
      - primo-explore-eluna-cypress
      - quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:e2e
    image: primo-explore-eluna-cypress
    depends_on:
    - web
    environment:
      DOMAIN: http://web:8003/primo-explore/search
      VIEW: ${VIEW-ASU}
      CYPRESS_BASE_URL: http://web:8003/primo-explore/
